### ISSUE TITLE
Things to remove

### ISSUE THREAD

**Issue by BryanHJH** [EuJin03/University-Recommendation-System#4]
@EuJin03 
# Feedback.h

Need to remove the `private` section of the class. Since Feedback is now a standalone class, we only need to have the contents of the feedback as the private attributes, don't need the pointers already. Keep my version of the `private` attributes. The `Feedback.cpp` is fine already, don't need to change anything there, just the header file. 

# FavUniList

I don't think we need this class or struct anymore. We can just use the Linked List class to do this. So can remove

# LL & Test

This was for testing, can also be removed. Maybe you can remove from your side, I accidentally pushed it together.

**Comment by EuJin03** [comment]
Removed
